<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>uk.gov.moj.cpp.progression</groupId>
        <artifactId>progression-parent</artifactId>
        <version>17.0.288-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>progression-performance-test</artifactId>

    <properties>
        <target.jdbc.url>jdbc:postgresql://localhost:5432/progression-view-store-db
        </target.jdbc.url>
        <target.jdbc.username>postgres</target.jdbc.username>
        <target.jdbc.password>postgres</target.jdbc.password>
        <target.jdbc.settingsKey />

        <jmeter.test.file>*.jmx</jmeter.test.file>
        <!-- Performance tests don't need compilation -->
        <maven.test.skip>true</maven.test.skip>
        <jacoco.skip>true</jacoco.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.dbunit</groupId>
            <artifactId>dbunit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>progression-performance-test</id>
            <properties>
                <maven.test.skip>false</maven.test.skip>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>dbunit-maven-plugin</artifactId>
                        <version>${dbunit-maven-plugin.version}</version>
                        <configuration>
                            <driver>org.postgresql.Driver</driver>
                            <dataTypeFactoryName>
                                org.dbunit.ext.postgresql.PostgresqlDataTypeFactory
                            </dataTypeFactoryName>
                            <format>csv</format>
                            <password>${target.jdbc.password}</password>
                            <settingsKey>${target.jdbc.settingsKey}</settingsKey>
                            <src>src/test/data</src>
                            <type>CLEAN_INSERT</type>
                            <url>${target.jdbc.url}</url>
                            <username>${target.jdbc.username}</username>
                        </configuration>
                        <executions>
                            <execution>
                                <id>load-performance-test-data</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>operation</goal>
                                </goals>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>org.dbunit</groupId>
                                <artifactId>dbunit</artifactId>
                                <version>${dbunit.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.postgresql</groupId>
                                <artifactId>postgresql</artifactId>
                                <version>${postgresql.driver.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                    <plugin>
                        <groupId>com.lazerycode.jmeter</groupId>
                        <artifactId>jmeter-maven-plugin</artifactId>
                        <version>${jmeter-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>jmeter-tests</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>jmeter</goal>
                                </goals>
                                <configuration>
                                    <jmeterPlugins>
                                        <plugin>
                                            <groupId>kg.apc</groupId>
                                            <artifactId>jmeter-plugins-standard</artifactId>
                                        </plugin>
                                    </jmeterPlugins>
                                    <customPropertiesFile>
                                        ${project.build.testOutputDirectory}/jmeter/properties/${target.properties}
                                    </customPropertiesFile>
                                    <testResultsTimestamp>false</testResultsTimestamp>
                                    <resultsFileFormat>csv</resultsFileFormat>
                                    <propertiesJMeter>
                                        <jmeter.save.saveservice.print_field_names>true
                                        </jmeter.save.saveservice.print_field_names>
                                        <jmeter.save.saveservice.successful>true
                                        </jmeter.save.saveservice.successful>
                                        <jmeter.save.saveservice.label>true
                                        </jmeter.save.saveservice.label>
                                        <jmeter.save.saveservice.time>true
                                        </jmeter.save.saveservice.time>
                                        <server>${target.host}</server>
                                        <port>${target.port}</port>
                                        <jmeter.get.progression.read.test.threads>
                                            ${jmeter.get.progression.read.test.threads}
                                        </jmeter.get.progression.read.test.threads>
                                    </propertiesJMeter>
                                    <testFilesIncluded>
                                        <jMeterTestFile>${jmeter.test.file}</jMeterTestFile>
                                    </testFilesIncluded>
                                </configuration>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>kg.apc</groupId>
                                <artifactId>jmeter-plugins-standard</artifactId>
                                <version>${jmeter-plugins-standard.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                    <plugin>
                        <groupId>uk.co.automatictester</groupId>
                        <artifactId>jmeter-lightning-maven-plugin</artifactId>
                        <version>${jmeter-lightning-maven-plugin}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>lightning</goal>
                                </goals>
                                <configuration>
                                    <mode>verify</mode>
                                    <testSetXml>src/test/resources/ci/lightning.xml</testSetXml>
                                    <jmeterCsv>
                                        target/jmeter/results/progression-performance-test.csv
                                    </jmeterCsv>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>
</project>
