<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.progression</groupId>
        <artifactId>progression-event</artifactId>
        <version>17.0.288-SNAPSHOT</version>
    </parent>
    <artifactId>progression-event-listener</artifactId>
    <packaging>war</packaging>

    <properties>
        <cpp.service-component>EVENT_LISTENER</cpp.service-component>
    </properties>

    <dependencies>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>event-listener</artifactId>

        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.progression</groupId>
            <artifactId>progression-viewstore-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.progression</groupId>
            <artifactId>progression-test-utilities</artifactId>
            <scope>test</scope>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.minidev</groupId>
            <artifactId>json-smart</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <!-- MI schema contract validation tests jar dependency-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <artifactId>mireportdata-progression-event-listener</artifactId>
                                    <groupId>uk.gov.moj.cpp.mi.reportdata</groupId>
                                    <version>RELEASE</version>
                                    <classifier>listener-tests</classifier>
                                    <type>jar</type>
                                    <outputDirectory>${project.build.directory}/test-classes
                                    </outputDirectory>
                                    <overWrite>true</overWrite>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
