<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.progression</groupId>
        <artifactId>progression-domain</artifactId>
        <version>17.0.288-SNAPSHOT</version>
    </parent>
    <artifactId>progression-domain-message</artifactId>
    <properties>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>
    <dependencies>
        <dependency>
            <groupId>uk.gov.moj.cpp.progression</groupId>
            <artifactId>progression-datatypes-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.progression</groupId>
            <artifactId>progression-domain-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-domain</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-testlib</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>criminal-court-public-model</artifactId>
            <version>${coredomain.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>common-core-domain</artifactId>
            <version>${coredomain.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.generators</groupId>
                <artifactId>pojo-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pojo-generation</id>
                        <configuration>
                            <basePackageName>uk.gov.moj.cpp.events.people</basePackageName>
                            <sourceDirectory>${project.basedir}/src/raml/json/schema
                            </sourceDirectory>
                            <generatorProperties implementation="uk.gov.justice.generation.pojo.core.PojoGeneratorProperties">
                                <plugins>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.AddHashcodeAndEqualsPlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.typemodifying.ReferenceCustomReturnTypePlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.typemodifying.FormatCustomReturnTypePlugin</plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddEventAnnotationToClassPlugin
                                    </plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.AddAdditionalPropertiesToClassPlugin</plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.MakeClassSerializablePlugin
                                    </plugin>
                                    <!--plugin>uk.gov.moj.cpp.pojoplugin.MutablePojoPlugin</plugin-->
                                </plugins>
                                <typeMappings>
                                    <typeMapping>
                                        <name>uuid</name>
                                        <type>reference</type>
                                        <implementation>java.util.UUID</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>datePattern</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>format</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date-time</name>
                                        <type>format</type>
                                        <implementation>java.time.ZonedDateTime</implementation>
                                    </typeMapping>
                                </typeMappings>
                            </generatorProperties>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>progression-datatypes-common</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.core.domain</groupId>
                        <artifactId>criminal-court-public-model</artifactId>
                        <version>${coredomain.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.core.domain</groupId>
                        <artifactId>common-core-domain</artifactId>
                        <version>${coredomain.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
