<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.progression</groupId>
        <artifactId>progression-parent</artifactId>
        <version>17.0.288-SNAPSHOT</version>
    </parent>
    <artifactId>progression-event</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>progression-event-indexer</module>
        <module>progression-event-listener</module>
        <module>progression-event-processor</module>
    </modules>
    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-adapter-generator-plugin</artifactId>
                <version>${framework.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.progression</groupId>
                        <artifactId>progression-event-sources</artifactId>
                        <classifier>yaml</classifier>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.progression</groupId>
                        <artifactId>progression-event-sources</artifactId>
                        <classifier>yaml</classifier>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>