<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.progression</groupId>
        <artifactId>progression-viewstore</artifactId>
        <version>17.0.288-SNAPSHOT</version>
    </parent>

    <artifactId>progression-viewstore-persistence</artifactId>
    <properties>
        <h2.version>1.4.196</h2.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Progression Dependencies -->
        <dependency>
            <groupId>uk.gov.moj.cpp.progression</groupId>
            <artifactId>progression-domain-message</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>persistence-deltaspike</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>utilities-core</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-common</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.event-store</groupId>
            <artifactId>test-utils-persistence</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>test-utils-logging-log4j</artifactId>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomee</groupId>
            <artifactId>openejb-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomee</groupId>
            <artifactId>openejb-server</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomee</groupId>
            <artifactId>openejb-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.deltaspike.modules</groupId>
            <artifactId>deltaspike-test-control-module-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.deltaspike.modules</groupId>
            <artifactId>deltaspike-test-control-module-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.deltaspike.cdictrl</groupId>
            <artifactId>deltaspike-cdictrl-openejb</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
